'use client';

import {useEffect,useRef,useState} from 'react';

const APP='Prep Master';
const TELEGRAM='https://t.me/prepmaster0';
const DEMO=false;

function logo(){return <div className="logo">PM</div>}
function escText(v){return v==null?'':String(v)}

export default function Home(){
 const [tab,setTab]=useState('batches'); const [batches,setBatches]=useState([]); const [enrolled,setEnrolled]=useState([]); const [search,setSearch]=useState(''); const [page,setPage]=useState({type:'home'}); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{try{setEnrolled(JSON.parse(localStorage.getItem('pm_enrolled')||'[]'))}catch{}; loadBatches(); if(!localStorage.getItem('pm_telegram_seen')) setTimeout(()=>setTelegramPopup(),600)},[]);
 async function loadBatches(){setLoading(true);setError('');try{const r=await fetch('/api/batches',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();const arr=Array.isArray(j)?j:(j.data||[]);setBatches(arr.map(normalizeBatch))}catch(e){setError('Unable to load batches. Check your API route and environment variables.')}finally{setLoading(false)}}
 function normalizeBatch(b){return {id:b.id??b.batch_id??b.course_id,title:b.title??b.name??'Untitled Batch',subtitle:b.subtitle??b.description??'Study batch',thumbnail:b.thumbnail??b.image??b.banner??'',isNew:Boolean(b.is_new||b.isNew||b.new)}}
 function saveEnroll(a){setEnrolled(a);localStorage.setItem('pm_enrolled',JSON.stringify(a))}
 function enroll(id){const key=String(id);const next=enrolled.includes(key)?enrolled:[...enrolled,key];saveEnroll(next);alert('Congratulations 🎉\n\nYou are successfully enrolled. You can find this batch in My Batches.');}
 function setTelegramPopup(){const ok=window.confirm('Welcome to Prep Master!\n\nLatest updates and announcements ke liye Telegram channel join karein.');localStorage.setItem('pm_telegram_seen','1');if(ok)window.open(TELEGRAM,'_blank','noopener,noreferrer')}
 async function openStudy(b){setPage({type:'study',batch:b,loading:true});try{const r=await fetch(`/api/batches/${encodeURIComponent(b.id)}/overview`,{cache:'no-store'});if(!r.ok)throw Error();const j=await r.json();const folders=j.data||j.folders||j?.response?.data||[];setPage({type:'study',batch:b,folders:normalizeFolders(folders)})}catch{setPage({type:'error',message:'Unable to open this batch. Check the overview API response.'})}}
 function normalizeFolders(a){return (Array.isArray(a)?a:[]).map(x=>({id:x.id??x.folder_id??x.entity_id,title:x.title??x.name??'Folder',count:x.count??x.total??x.items_count??''}))}
 async function openFolder(folder){setPage({type:'lectures',batch:page.batch,folder,loading:true});try{const r=await fetch(`/api/batches/${encodeURIComponent(page.batch.id)}/folders/${encodeURIComponent(folder.id)}/content`,{cache:'no-store'});if(!r.ok)throw Error();const j=await r.json();const a=j.data||j.items||j.content||j?.response?.data||[];setPage({type:'lectures',batch:page.batch,folder,lectures:normalizeLectures(a)})}catch{setPage({type:'error',message:'Unable to load folder content.'})}}
 function normalizeLectures(a){return (Array.isArray(a)?a:[]).map(x=>({id:x.id??x.entity_id??x.content_id,title:x.title??x.name??'Lecture',duration:x.duration??'',locked:Boolean(x.locked||x.is_locked||x.isLocked),content_id:x.content_id??x.id,vdc_id:x.vdc_id??x.vdcId??''}))}
 async function openLecture(l){if(l.locked){alert('This lecture is locked or unavailable.');return}setPage({type:'player',batch:page.batch,lecture:l,loading:true});try{const qs=new URLSearchParams({course_id:String(page.batch.id)});if(l.vdc_id)qs.set('vdc_id',String(l.vdc_id));if(l.content_id)qs.set('content_id',String(l.content_id));const r=await fetch(`/api/content/${encodeURIComponent(l.id)}/playback?${qs}`,{cache:'no-store'});if(!r.ok)throw Error();const j=await r.json();const streamUrl=j.streamUrl||j.playbackUrl||j.url||j.data?.streamUrl||j.data?.playbackUrl;if(!streamUrl)throw Error();setPage({type:'player',batch:page.batch,lecture:l,streamUrl})}catch{setPage({type:'error',message:'Playback unavailable. The backend must return an authorized playback URL for this lecture.'})}}
 const visible=(tab==='my'?batches.filter(b=>enrolled.includes(String(b.id))):batches).filter(b=>String(b.title).toLowerCase().includes(search.toLowerCase()));
 if(page.type==='study')return <Study page={page} back={()=>setPage({type:'home'})} openFolder={openFolder}/>;
 if(page.type==='lectures')return <Lectures page={page} back={()=>openStudy(page.batch)} openLecture={openLecture}/>;
 if(page.type==='player')return <Player page={page} back={()=>setPage({type:'lectures',batch:page.batch,folder:page.folder,lectures:[]})}/>;
 if(page.type==='error')return <div className="container"><div className="loading">{page.message}<br/><button className="btn dark" onClick={()=>setPage({type:'home'})}>Back Home</button></div></div>;
 return <div className="app"><header className="header"><div className="header-inner container">{logo()}<div className="grow"><div className="brand">{APP}</div><div className="small muted">Learn smarter. Grow faster.</div></div><button className="btn" onClick={()=>window.open(TELEGRAM,'_blank','noopener,noreferrer')}>Join Telegram</button></div></header><main className="main container"><section className="hero"><div className="hero-row">{logo()}<div><div className="small muted">WELCOME TO</div><h1>Prep Master</h1></div></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search batches..."/></section><div className="section-row"><h2>{tab==='my'?'My Batches':'All Batches'}</h2><span className="small muted">{visible.length} batches</span></div>{loading?<div className="loading">Loading batches...</div>:error?<div className="error">{error}</div>:visible.length?<div className="grid">{visible.map(b=><BatchCard key={b.id} b={b} enrolled={enrolled.includes(String(b.id))} enroll={()=>enroll(b.id)} study={()=>openStudy(b)}/>)}</div>:<div className="empty">{tab==='my'?"You haven't enrolled in any batch yet.":'No batches found.'}</div>}</main><nav className="bottom"><div className="bottom-inner"><button className={'navbtn '+(tab==='my'?'active':'')} onClick={()=>setTab('my')}>📖<br/><b>My Batches</b></button><button className={'navbtn '+(tab==='batches'?'active':'')} onClick={()=>setTab('batches')}>📚<br/><b>Batches</b></button></div></nav></div>
}

function BatchCard({b,enrolled,enroll,study}){return <article className="card">{b.thumbnail?<img className="thumb" src={b.thumbnail} alt=""/>:<div className="thumb">📚</div>}<div className="card-body">{b.isNew&&<span className="tag">NEW</span>}<div className="title">{escText(b.title)}</div><div className="small muted" style={{marginTop:4}}>{escText(b.subtitle)}</div><div className="actions"><button className="btn dark" onClick={enroll}>{enrolled?'ENROLLED ✓':'+ ENROLL'}</button><button className="btn" onClick={study}>LET'S STUDY →</button></div></div></article>}
function Study({page,back,openFolder}){return <div className="container"><div className="study-head"><button className="back" onClick={back}>←</button>{logo()}<div className="grow"><b>{page.batch.title}</b><div className="small muted">Batch ID: {page.batch.id}</div></div></div>{page.loading?<div className="loading">Loading course content...</div>:<main className="main"><div className="hero"><b>📚 Course Content</b><div className="small muted">Open a folder to view its content.</div></div>{page.folders?.map(f=><button className="folder" key={f.id} onClick={()=>openFolder(f)}><div className="iconbox">📁</div><div className="grow"><b>{f.title}</b><div className="small muted">{f.count} items</div></div>›</button>)}</main>}</div>}
function Lectures({page,back,openLecture}){return <div className="container"><div className="study-head"><button className="back" onClick={back}>←</button><b>Lectures</b></div><main className="main">{page.loading?<div className="loading">Loading lectures...</div>:page.lectures?.map(l=><button className="lecture" key={l.id} onClick={()=>openLecture(l)}><div className="iconbox">{l.locked?'🔒':'▶️'}</div><div className="grow"><b>{l.title}</b><div className="small muted">{l.duration||'Video lesson'}</div></div>›</button>)}</main></div>}
function Player({page,back}){const ref=useRef(null);useEffect(()=>{if(!page.streamUrl||!ref.current)return;let hls=null;const video=ref.current;if(video.canPlayType('application/vnd.apple.mpegurl'))video.src=page.streamUrl;else{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/hls.js@1.5.17';s.onload=()=>{if(window.Hls&&window.Hls.isSupported()){hls=new window.Hls();hls.loadSource(page.streamUrl);hls.attachMedia(video)}};document.body.appendChild(s)}return()=>{if(hls)hls.destroy()}},[page.streamUrl]);return <div className="player"><div className="study-head" style={{background:'#050505',color:'#fff',borderColor:'#222'}}><button className="back" onClick={back}>←</button><b>{page.lecture?.title||'Lecture'}</b></div>{page.loading?<div className="loading">Getting authorized playback URL...</div>:<main className="player-main"><video ref={ref} className="video" controls playsInline/><p className="small" style={{color:'#aaa'}}>Playback URL is supplied by your authorized backend for this lecture.</p></main>}</div>}
